
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'yapl_mnmleftORORleftANDANDleftEQUALEQUALleftLTLEGTGEleftPLUSMINUSleftTIMESDIVIDErightUMINUSrightNOTANDAND COMMA DIVIDE EQUAL EQUALEQUAL FALSE GE GT IDENTIFIER LBRACE LE LPAREN LT MINUS NOT NUMBER OROR PLUS RBRACE RPAREN SEMICOLON STRING TIMES TRUE\n    yapl_mnm : exp\n             | assign_identifier\n             | empty\n\n    empty :\n    assign_identifier : IDENTIFIER EQUAL exp\n    \n    exp : exp TIMES exp\n        | exp DIVIDE exp\n        | exp PLUS exp\n        | exp MINUS exp\n    exp : MINUS exp %prec UMINUS\n    exp : NUMBER\n    \n    exp : IDENTIFIER\n    '
    
_lr_action_items = {'MINUS':([0,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,],[5,11,5,-11,-12,5,5,5,5,-10,-12,5,-6,-7,-8,-9,11,]),'NUMBER':([0,5,8,9,10,11,14,],[6,6,6,6,6,6,6,]),'IDENTIFIER':([0,5,8,9,10,11,14,],[7,13,13,13,13,13,13,]),'$end':([0,1,2,3,4,6,7,12,13,15,16,17,18,19,],[-4,0,-1,-2,-3,-11,-12,-10,-12,-6,-7,-8,-9,-5,]),'TIMES':([2,6,7,12,13,15,16,17,18,19,],[8,-11,-12,-10,-12,-6,-7,8,8,8,]),'DIVIDE':([2,6,7,12,13,15,16,17,18,19,],[9,-11,-12,-10,-12,-6,-7,9,9,9,]),'PLUS':([2,6,7,12,13,15,16,17,18,19,],[10,-11,-12,-10,-12,-6,-7,-8,-9,10,]),'EQUAL':([7,],[14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'yapl_mnm':([0,],[1,]),'exp':([0,5,8,9,10,11,14,],[2,12,15,16,17,18,19,]),'assign_identifier':([0,],[3,]),'empty':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> yapl_mnm","S'",1,None,None,None),
  ('yapl_mnm -> exp','yapl_mnm',1,'p_yapl_mnm','yapl_mnm_parser.py',49),
  ('yapl_mnm -> assign_identifier','yapl_mnm',1,'p_yapl_mnm','yapl_mnm_parser.py',50),
  ('yapl_mnm -> empty','yapl_mnm',1,'p_yapl_mnm','yapl_mnm_parser.py',51),
  ('empty -> <empty>','empty',0,'p_empty','yapl_mnm_parser.py',57),
  ('assign_identifier -> IDENTIFIER EQUAL exp','assign_identifier',3,'p_assign_identifier','yapl_mnm_parser.py',64),
  ('exp -> exp TIMES exp','exp',3,'p_exp','yapl_mnm_parser.py',70),
  ('exp -> exp DIVIDE exp','exp',3,'p_exp','yapl_mnm_parser.py',71),
  ('exp -> exp PLUS exp','exp',3,'p_exp','yapl_mnm_parser.py',72),
  ('exp -> exp MINUS exp','exp',3,'p_exp','yapl_mnm_parser.py',73),
  ('exp -> MINUS exp','exp',2,'p_exp_uminus','yapl_mnm_parser.py',78),
  ('exp -> NUMBER','exp',1,'p_exp_number','yapl_mnm_parser.py',83),
  ('exp -> IDENTIFIER','exp',1,'p_exp_identifier','yapl_mnm_parser.py',89),
]
